services:
  app:
    image: dgarcia51/blogadmin:latest
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
